---
sidebar: sidebar 
permalink: reference-iam-storage-roles.html 
keywords: storage roles, Storage admin, Storage viewer, System health specialist, ONTAP management, storage governance, identity and access management, access roles, rbac, netapp console local 
summary: ユーザーに NetApp Console ローカル展開のストレージ管理機能へのアクセス権限を付与するには、次のロールを割り当てることができます。ユーザーには、ストレージを管理するための管理者ロール、または監視のための閲覧者ロールを割り当てることができます。 
---
= NetApp Console ローカル展開のストレージアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ユーザーに NetApp Console ローカル展開のストレージ管理機能へのアクセス権限を付与するには、次のロールを割り当てることができます。ユーザーには、ストレージを管理するための管理者ロール、または監視のための閲覧者ロールを割り当てることができます。

管理者は、以下のストレージリソースおよび機能に対して、ユーザーにストレージロールを割り当てることができます。

ストレージリソース：

* オンプレミス ONTAP クラスター


コンソールサービスと機能：

* ストレージの健全性機能


.NetApp Console ローカル展開におけるストレージロールの例
多国籍企業であるXYZ Corporation は、ストレージエンジニアとストレージ管理者からなる大規模なチームを擁しています。これにより、このチームは担当地域のストレージ資産を管理できる一方で、ユーザー管理やライセンス管理といった Console のコアなローカル展開タスクへのアクセスを制限することができます。

12人のチーム内で、2人のユーザーに *Storage viewer* ロールが付与され、割り当てられた Console ローカル展開フリートに関連付けられたストレージリソースを監視できるようになります。残りの9名には *Storage admin* ロールが付与されます。このロールには、ソフトウェアアップデートの管理、Console ローカル展開を通じた ONTAP System Manager へのアクセス、およびストレージリソースの検出（システムの追加）が含まれます。チームのメンバーのうち1名に *System health specialist* ロールが割り当てられ、担当地域のストレージリソースの健全性を管理できますが、システムの変更や削除はできません。この担当者は、割り当てられたフリートのストレージリソースに対してソフトウェアアップデートを実行することもできます。

組織には、ユーザー管理やライセンス管理など、Console のローカル展開のあらゆる側面を管理できる *Organization admin* ロールを持つユーザーが2名、および割り当てられたフォルダやフリートの Console のローカル展開管理タスクを実行できる *Folder or fleet admin* ロールを持つユーザーが複数います。

以下の表は、各ストレージロールが実行するアクションを示しています。

[cols="40,20a,20a,20a"]
|===
| 機能とアクション | Storage Admin | システムヘルススペシャリスト | ストレージビューア 


4+| *ストレージ管理*： 


| 新しいリソースを見つける（システムを追加する）  a| 
はい
 a| 
はい
 a| 
×



| 追加されたシステムを表示  a| 
はい
 a| 
はい
 a| 
×



| コンソールからシステムを削除する  a| 
はい
 a| 
×
 a| 
×



| システムを変更する  a| 
はい
 a| 
×
 a| 
×



4+| *システム マネージャ アクセス* 


| 認証情報を入力できます  a| 
はい
 a| 
はい
 a| 
×

|===