---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, Organization admin, Folder or fleet admin, Super admin, Federation admin, platform roles, role, iam, identity and access management, netapp console local 
summary: プラットフォームロールをユーザーに割り当てて、NetApp Console のローカル展開の管理、ロールの割り当て、ユーザーの追加、およびフェデレーションの管理に関する権限を付与します。 
---
= NetApp Console ローカル展開プラットフォームのアクセスロール
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
プラットフォームロールをユーザーに割り当てて、NetApp Console のローカル展開の管理、ロールの割り当て、ユーザーの追加、フリートの作成、およびユーザ認証の管理に関する権限を付与します。

.大規模多国籍企業における組織内役割の例
XYZ Corporationはデータのストレージ アクセスを地域別（北米、ヨーロッパ、アジア太平洋）に整理し、地域ごとの統制と一元的な監視体制を両立させています。

XYZ Corporation の Console ローカル展開における *Organization admin* は、初期組織と各地域ごとに個別のフォルダを作成します。各地域の *Folder or fleet admin* は、その地域のフォルダ内にフリート（および関連するリソース）を整理します。

*Folder or fleet admin* の役割を持つ地域管理者は、リソースやユーザーを追加することで、フォルダーを積極的に管理します。これらの地域管理者は、管理するフォルダやフリートを追加、削除、または名前変更することもできます。*Organization admin* は、新しいリソースに対する権限を継承し、組織全体におけるストレージ使用状況の可視性を維持します。

同一組織内では、1人のユーザーに *Federation admin* の役割が割り当てられ、組織と所属企業の IdP とのフェデレーションを管理します。このユーザーは、フェデレーション組織を追加または削除することはできますが、組織内のユーザーやリソースを管理することはできません。*Organization admin* は、フェデレーションの状態を確認したり、フェデレーションに参加している組織を表示したりするために、ユーザーに *Federation viewer* の役割を割り当てます。

以下の表は、各 Console ローカル展開プラットフォームロールが実行できるアクションを示しています。



[[organization-administration-roles]]
[[organization-admin-roles]]
== 組織管理の役割

[cols="2,1,1"]
|===
| Task | 組織管理者 | フォルダまたはフリート管理者 


| コンソールのローカル展開環境からシステムを作成、変更、または削除します（システムの追加または検出） | はい | はい 


| フォルダーとフリートの作成、削除を含む | はい | × 


| 既存のフォルダとフリートの名前を変更する | はい | はい 


| 役割を割り当ててユーザーを追加する | はい | はい 


| リソースをフォルダーとフリートに関連付ける | はい | はい 


| サポートへの登録およびコンソールからのケースの送信 | はい | はい 


| 明示的なアクセスロールに関連付けられていないデータサービスを使用する | はい | はい 


| 監査ページと通知を表示する | はい | はい 
|===


[[federation-roles]]
== フェデレーションロール

[cols="2,1,1"]
|===
| Task | フェデレーション管理者 | フェデレーションビューアー 


| ディレクトリサービス統合の作成と更新 | はい | × 


| フェデレーションとその詳細を表示する | はい | はい 
|===


[[super-admin-and-viewer-roles]]
[[super-admin-roles]]
== スーパー管理者と閲覧者の役割

*Super admin* ロールは、Console 機能、ストレージ、およびデータサービスを管理するための完全なアクセス権を提供します。このロールは、管理運営やガバナンスを監督する方に適しています。一方、*Super viewer* ロールは読み取り専用アクセスを提供し、変更を加えることなく可視性を必要とする監査担当者や関係者に最適です。

組織は、セキュリティリスクを最小限に抑え、最小権限の原則に沿うために、*Super admin* アクセスの使用を控えめにすべきです。ほとんどの組織は、リスクを軽減し監査性を向上させるために、必要な権限のみを持つきめ細かなロールを割り当てるべきです。

.スーパーロールの例
ABC Corporation には5人の小規模なチームがあり、データサービスおよびストレージ管理のために NetApp Console を活用しています。複数の役割を分担する代わりに、ユーザー管理やリソース構成を含むすべての管理業務を担当する2人の上級チームメンバーに *Super admin* ロールを割り当てています。残りの3人のチームメンバーには *Super viewer* ロールが割り当てられており、設定を変更する権限なしにストレージの状態とデータサービスのステータスを監視できます。

[cols="2,1"]
|===
| ロール | 継承されたロール 


 a| 
スーパー管理者
 a| 
* 組織管理者
* フォルダまたはフリート管理者
* バックアップとリカバリのスーパー管理者
* Storage Admin




 a| 
スーパービューアー
 a| 
* 組織ビューア
* バックアップビューアー
* ストレージビューア


|===