---
sidebar: sidebar 
permalink: task-iam-manage-members-permissions.html 
keywords: user, directory user, directory users, service account, member, role, permissions, organization, fleet, folder, iam, identity and access management, access roles, add members, grant permissions, AD, Active Directory, directory services 
summary: メンバーを追加し、ロールを割り当てることで、組織のリソース階層のさまざまなレベルにわたって権限を付与できます。 
---
= メンバーを NetApp Console ローカル展開組織に追加する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
メンバーを NetApp Console のローカル展開組織に追加し、ユーザー、サービスアカウント、ディレクトリユーザーに対して、組織、フォルダ、またはフリートレベルでのアクセス権を付与するロールを割り当てます。

.必要なアクセスロール
スーパー管理者、組織管理者、またはフォルダ管理者もしくはフリート管理者（管理対象のフォルダおよびフリートの場合）。link:reference-iam-predefined-roles.html["アクセスロールについて"]。



[[before-you-begin]]
== 開始する前に

* 組織に合ったフォルダとフリートの階層構造を作成してください。link:task-iam-manage-folders-fleets.html["フォルダとフリートを使ってリソースを整理する方法を説明します。"]。
* メンバーのアクセス権を割り当てる前に、リソースを適切なフリートに関連付けてください。link:task-iam-manage-resources.html["フォルダとフリート内のリソースを管理する方法について説明します。"]。
* ディレクトリユーザーを追加する場合は、まずディレクトリサービスを統合してください。link:task-iam-active-directory-integrate.html["ディレクトリサービスとの統合方法をご確認ください"]。




[[understand-how-access-is-granted-in-netapp-console-local-deployment]]
== NetApp Console ローカル展開におけるアクセス許可の仕組みを理解する

NetApp Console はロールベースアクセス制御（RBAC）を使用して権限を管理します。必要なアクセス権限を付与するために、メンバーにロールを割り当ててください。各ロールは、特定のリソースに対して許可される操作を定義します。

NetApp Console ローカル展開でのアクセス許可に関する注意事項：

* ユーザーがリソースにアクセスするには、各ユーザーを組織に明示的に追加し、少なくとも1つのロールを割り当てる必要があります。
* 組織レベルまたはフォルダレベルで割り当てた役割は子スコープに継承されるため、メンバーが必要な場所でのみアクセスできるように、割り当てスコープを慎重に選択してください。link:concept-iam-rbac.html#role-inheritance["NetApp Console ローカル展開におけるロール継承について"]。




[[add-members-to-your-organization]]
[[add-members]]
== 組織にメンバーを追加する

NetApp Console は、ユーザーアカウント、ディレクトリユーザー、サービスアカウントの3種類のメンバーをサポートしています。


NOTE: ユーザーを追加する前に、Console のローカル展開で使用するメールサーバーを最初に設定する必要があります。link:task-console-configure-notifications-delivery.html["メールサーバーの設定方法について説明します。"]

ディレクトリユーザーは統合ディレクトリサービスを通じて認証されますが、Console のローカル展開では、各ディレクトリユーザーを個別に追加し、ロールを割り当てる必要があります。Console でサービスアカウントを直接作成します。

Console のローカル展開にアクセスするには、すべてのメンバーに少なくとも1つのロールが明示的に割り当てられている必要があります。

メンバーを追加する際は、メンバーがアクセスする必要のある組織、フォルダー、またはフリートを選択し、必要な初期ロールを割り当ててください。



[[add-a-user-account]]
=== ユーザーアカウントを追加する

組織、フォルダ、またはフリートにユーザーを追加してリソースにアクセスできるようにするには、組織管理者、フォルダ管理者、またはフリート管理者のいずれかの役割を持っている必要があります。

.手順
. 「管理」＞「IDとアクセス」を選択してください。
. 「メンバー」を選択します。
. 「メンバーを追加」を選択します。
. *メンバータイプ*については、*ユーザー*を選択したままにしてください。
. 「ユーザーのメールアドレス」には、ユーザーが作成したログインに関連付けられているメールアドレスを入力してください。
. 「組織、フォルダ、またはフリートを選択」セクションを使用して、メンバーがアクセスする必要がある場所を選択します。
+
次の点に注意してください。

+
** 権限のあるフォルダーとフリートのみを選択できます。
** 組織またはフォルダを選択すると、そのメンバーにそのすべてのコンテンツへのアクセス権限が付与されます。
** 組織管理者ロールは、組織レベルでのみ割り当てることができます。


. *カテゴリを選択*してから、選択した組織、フォルダー、またはフリートに対してメンバーに必要な初期権限を付与する*ロール*を選択してください。
+
link:reference-iam-predefined-roles.html["アクセスロールについて"].

. より多くのフォルダー、フリート、またはロールへのアクセス権を付与するには、*ロールの追加* を選択し、フォルダー、フリート、またはロールのカテゴリを選択して、ロールを選択します。
. *追加*を選択します。
+
コンソールはユーザーに指示をメールで送信します。





[[add-a-service-account]]
[[service-account]]
=== サービスアカウントを追加する

タスクを自動化したり、Console APIに安全に接続したりする必要がある場合は、サービスアカウントを追加してください。アカウントを作成したら、そのクライアントIDとクライアントシークレットをコピーして、使用する連携機能に渡してください。

.手順
. 「管理」＞「IDとアクセス」を選択してください。
. 「メンバー」を選択します。
. 「メンバーを追加」を選択します。
. 「メンバータイプ」には「サービスアカウント」を選択してください。
. サービスアカウントの名前を入力してください。
. 「組織、フォルダ、またはフリートを選択」セクションを使用して、サービスアカウントがアクセスする必要がある場所を選択します。
+
次の点に注意してください。

+
** 権限のあるフォルダーとフリートのみを選択できます。
** 組織またはフォルダを選択すると、メンバーはその組織またはフォルダ内のすべてのコンテンツに対する権限が付与されます。
** 組織管理者ロールは、組織レベルでのみ割り当てることができます。


. 「カテゴリ」を選択し、次に、選択した組織、フォルダー、またはフリートに対してサービスアカウントに必要な初期権限を付与する「ロール」を選択します。
+
link:reference-iam-predefined-roles.html["アクセスロールについて"].

. より多くのフォルダー、フリート、またはロールへのアクセス権を付与するには、*ロールの追加* を選択し、フォルダー、フリート、またはロールのカテゴリを選択して、ロールを選択します。
. クライアントIDとクライアントシークレットをダウンロードまたはコピーしてください。
+
コンソールにはクライアントシークレットが一度だけ表示されます。安全な場所にコピーしておいてください。紛失しても後で再作成できます。

. 「閉じる」を選択します。




[[add-a-directory-user-to-your-organization]]
== 組織にディレクトリユーザーを追加する

統合ディレクトリサービスからユーザーを追加し、最初のロールを付与します。例えば、Active Directory から新しいストレージエンジニアを追加し、 `Production-US-East`フリートでストレージ管理者ロールを割り当てることで、そのフリートで作業できるようにします。

ディレクトリユーザーを追加するには、まずディレクトリサービスを設定する必要があります。link:task-iam-active-directory-integrate.html["ディレクトリサービスとの統合方法をご確認ください"]。

.手順
. 「管理」＞「IDとアクセス」を選択してください。
. 「メンバー」を選択します。
. 「メンバーを追加」を選択します。
. 「メンバータイプ」には「ディレクトリユーザー」を選択してください。
. 「ユーザーのメールアドレス」には、追加したいディレクトリユーザーのメールアドレスを入力してください。このメールアドレスは、ディレクトリ内でユーザーのログインに関連付けられているメールアドレスと一致している必要があります。
. 「組織、フォルダ、またはフリートを選択」セクションを使用して、ディレクトリユーザーがアクセスする必要がある場所を選択します。
+
次の点に注意してください。

+
** 権限のあるフォルダーとフリートのみを選択できます。
** 組織またはフォルダを選択すると、メンバーはその組織またはフォルダ内のすべてのコンテンツに対する権限が付与されます。
** 組織管理者ロールは、組織レベルでのみ割り当てることができます。


. *カテゴリ*を選択し、次に*役割*を選択して、選択した組織、フォルダー、またはフリートに対してディレクトリユーザーが必要とする初期権限を付与します。
+
link:reference-iam-predefined-roles.html["アクセスロールについて"].

. ユーザーに他のフォルダー、フリート、またはロールへの追加アクセス権を付与するには、「ロールの追加」を選択し、フォルダーまたはフリート、ロールのカテゴリを選択して、ロールを選択します。

