---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: 監査ページから、ユーザーアクティビティ（UIとAPIの両方から開始されたもの）を監査できます。また、コンソールが実行している操作のステータスを監視して、対処が必要な問題がないかを確認できます。監査ページからステータスを確認したり、監査ログをお客様独自のsyslogサーバに送信するように設定したりできます。 
---
= NetApp Consoleのローカル デプロイ アクティビティの監査
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
監査ページから UI と API の両方から開始されたユーザーアクティビティを監査でき、NetApp Console のローカル展開における操作のステータスとそれを開始したユーザーを監視できます。

.必須の役割
スーパー管理者、組織管理者、フォルダおよびフリート管理者、運用サポートアナリスト、スーパービューアー、組織ビューアー、またはフォルダおよびフリートビューアー。link:reference-iam-predefined-roles.html["アクセスロールについて"]。

コンソールのローカル展開で監査アクティビティを表示したり、監査ログのCSVをダウンロードしたり、Webhookを使用して監査ログをお客様独自のsyslogサーバーに送信するように設定したりできます。



[[audit-user-activity-from-the-audit-page]]
== 監査ページからユーザーアクティビティを監査する

監査ページを使用して、誰がどのような操作を行ったか、またはその操作のステータスを確認できます。

監査ページには、組織内でユーザーが行った操作が表示されます。例えば、誰が組織にメンバーを追加したか、フリートが正常に削除されたかを確認できるほか、組織内でユーザーが行ったその他のストレージ管理操作も確認できます。

監査ログには、以下のサービスのアクティビティが表示されます：

* テナント管理：ユーザーの追加、フリートの作成、リソースの関連付けなど、組織の管理に関連する操作。
* ストレージ管理：ストレージリソースの管理に関連する操作。
* フェデレーション：フェデレーションの管理に関連する操作。例えば、フェデレーションの作成、フェデレーション組織の追加または削除など。


.手順
. *「管理」>「監査」*を選択してください。
. 表の上にあるフィルターを使用して、表に表示されるアクションを変更できます。
+
例えば、*サービス* フィルターを使用して特定のサービスに関連するアクションを表示したり、*ユーザー* フィルターを使用して特定のユーザーアカウントに関連するアクションを表示したりできます。





[[filter-audit-logs-for-identity-and-access-management-actions]]
=== IDとアクセス管理アクションの監査ログをフィルタリングする

メンバーの追加、フリートの作成、リソースの削除など、組織の管理に関連する操作のみを表示するには、監査ログをTenancyサービスでフィルタリングします。

.手順
. *「管理」>「監査」*を選択してください。
. フィルターを使用して結果を絞り込んでください。「サービス」を選択し、次に「テナント」を選択してください。
. 結果をさらに絞り込むには、他のフィルターを使用してください。
+
例えば、*ユーザー*フィルターを使用して、特定のユーザーアカウントによって実行されたIAMアクションを表示します。





[[download-audit-logs-from-the-audit-page]]
=== 監査ページから監査ログをダウンロードする

監査ページから監査ログをCSVファイルとしてダウンロードできます。これにより、組織内でユーザーが行った操作の記録を保持することができます。ダウンロードされたCSVファイルには、監査ページのフィルターや表示列に関係なく、すべての監査ログ列が含まれます。

.手順
. 「監査」ページで、表の右上隅にあるダウンロードアイコンを選択します。

