---
sidebar: sidebar 
permalink: task-console-local-vm-config.html 
keywords: Console local VM, vcenter, esxi, vm maintenance, Console local maintenance, Console local operating system, Console local host 
summary: コンソールのローカル展開をデプロイした後でも、既存のvCenterまたはESXiホストに変更を加えることができます。 
---
= NetApp Consoleのローカルデプロイ用のvCenterまたはESXiホストのメンテナンス
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console ローカルデプロイメントでは、コンソールローカルデプロイメントをデプロイした後でも、既存の vCenter または ESXi ホストに変更を加えることができます。

VMウェブコンソールを使用して、以下のメンテナンス作業を実行します。

* コンソールのローカル展開を再起動します
* 静的ルートを更新する
* 検索ドメインを更新する


.制限事項
メンテナンスコンソールでは、IPアドレス、DNS、ゲートウェイに関する情報を閲覧することのみ可能で、更新はできません。



[[access-the-vm-maintenance-console]]
== VMメンテナンスコンソールにアクセスします

vSphereクライアントからメンテナンスコンソールにアクセスできます。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。




[[change-the-maint-user-password]]
=== maintユーザーのパスワードを変更する

 `maint`ユーザーのパスワードを変更できます。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
. 入力 `1`して `System Configuration`メニューを表示します。
.  `1`を入力してメンテナンスユーザーのパスワードを変更し、画面の指示に従ってください。




[[view-network-settings-for-the-console-local-deployment-vm]]
=== コンソールのローカル展開VMのネットワーク設定を表示する

ネットワークの問題を確認またはトラブルシューティングするには、vSphereクライアントでコンソールローカルデプロイメントVMのネットワーク設定を表示します。以下のネットワーク設定は表示のみ可能で、更新はできません：IPアドレスとDNSの詳細。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
.  `2`を入力して `Network Configuration`メニューを表示します。
. 1から6までの数字を入力すると、対応するネットワーク設定が表示されます。




[[update-the-static-routes-for-the-console-local-deployment-vm]]
=== コンソールローカルデプロイメントVMの静的ルートを更新します

必要に応じて、コンソールローカルデプロイメントVMの静的ルートを追加、更新、または削除します。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
.  `2`を入力して `Network Configuration`メニューを表示します。
. 静的ルートを更新するには、 `7`を入力し、画面の指示に従ってください。
. Enterキーを押します。
. 必要に応じて、さらに変更を加えてください。
.  `9`を押して変更を確定します。




[[update-domain-search-settings-for-the-console-local-deployment-vm]]
=== コンソールローカル展開VMのドメイン検索設定を更新する

コンソールのローカルデプロイメントVMの検索ドメイン設定を更新できます。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
.  `2``を入力して `Network Configuration`メニューを表示します。
. 入力 `8`してドメイン検索設定を更新し、画面の指示に従ってください。
. Enterキーを押します。
. 必要に応じて、さらに変更を加えてください。
.  `9`を押して変更を確定します。




[[access-the-console-local-deployment-diagnostic-tools]]
[[connect-vcenter-host]]
=== コンソールのローカル展開診断ツールにアクセスする

コンソールのローカル展開に関する問題をトラブルシューティングするには、診断ツールにアクセスしてください。NetApp サポートから、問題のトラブルシューティング時にこの操作を求められる場合があります。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
.  `3`を入力して、サポートと診断メニューを表示します。
. 入力 `1`して診断ツールにアクセスし、画面の指示に従ってください。




[[access-the-console-local-deployment-diagnostic-tools-remotely]]
=== コンソールのローカル展開診断ツールにリモートでアクセスする

Puttyなどのツールを使用して、診断ツールにリモートでアクセスできます。ワンタイムパスワードを割り当てることで、コンソールのローカルデプロイメントVMへのSSHアクセスを有効にします。

SSHアクセスにより、コピー＆ペーストなどの高度なターミナル機能を利用できるようになります。

.手順
. vSphereクライアントを開き、vCenterにログインしてください。
. Console のローカル展開をホストする VM インスタンスを選択します。
. 「Launch Web Console」を選択します。
. VMインスタンス作成時に指定したユーザー名とパスワードを使用して、VMインスタンスにログインします。ユーザー名は `maint`で、パスワードはVMインスタンス作成時に指定したものです。
.  `3`を入力して `Support and Diagnostics`メニューを表示します。
.  `2`を入力して診断ツールにアクセスし、画面の指示に従って24時間で有効期限が切れるワンタイムパスワードを設定してください。
. PuttyなどのSSHツールを使用して、ユーザー名 `diag`と設定したワンタイムパスワードを使用して、コンソールのローカルデプロイメントVMに接続します。

