---
sidebar: sidebar 
permalink: task-provisioning-manual.html 
keywords: provisioning, provision storage, create volume, create LUN, ONTAP, storage class, fleet, NAS, SAN, manual provisioning, netapp console 
summary: NetApp Console ローカル展開を使用してストレージ リソースをプロビジョニングします。 
---
= NetApp Console ローカル展開でのストレージ プロビジョニング
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console のローカルデプロイメントでボリュームと LUN をプロビジョニングして、ワークロードに必要なストレージリソースを利用可能にします。プロビジョニングの際に、オプションでストレージクラスを選択して、定義済みのストレージポリシーと組織標準を適用できます。

.必要なアクセスロール
スーパー管理者、組織管理者、フォルダまたはフリート管理者、またはストレージ管理者。link:reference-iam-predefined-roles.html["アクセスロールについて"]。



[[provision-a-volume]]
== ボリュームをプロビジョニングする

.手順
. 「ストレージ」>「管理」を選択します。
. 「Fleets」を選択します。
. プロビジョニングを行うフリートを選択してください。
. *追加*を選択します。
. メニューから「Volume」を選択してください。
. *ボリュームの詳細*：
+
.. ボリューム名を入力してください。
.. 容量を入力してください（必要に応じて単位を選択してください）。
.. （オプション）ストレージクラスポリシーを適用するストレージクラスを選択します。選択しない場合、ボリュームはストレージクラスポリシーなしでプロビジョニングされます。


. *システム詳細*の下：
+
.. 選択したフリートに適したシステムの中から、1つのシステムを選択してください。
.. Storage VMを選択します。


. 「ホスト（NAS）の詳細」で、ホストがボリュームにアクセスする方法を選択します：
+
.. NFSによるエクスポート（エクスポートポリシーによって、どのNFSホストがボリュームにアクセスできるかを制御できます）
.. SMB/CIFS による共有


. *追加*を選択します。




[[provision-a-lun]]
== LUNをプロビジョニングする

.手順
. 「ストレージ」>「管理」を選択します。
. 「Fleets」を選択します。
. プロビジョニングを行うフリートを選択してください。
. *追加*を選択します。
. メニューから「LUNs」を選択してください。
. *LUN ストレージの詳細*：
+
.. 接頭辞名を入力してください。
.. そのプレフィックスを使用して作成するLUNの数を入力してください。
.. LUNごとの容量を入力してください（必要に応じて単位を選択してください）。
.. （オプション）ストレージクラスポリシーを適用するストレージクラスを選択します。選択しない場合、LUN はストレージクラスポリシーなしでプロビジョニングされます。


. *システム詳細*の下：
+
.. システムを選択してください（プロンプトが表示された場合）。
.. Storage VMを選択します。


. *ホスト（SAN）の詳細*で、ホストがボリュームにアクセスする方法を選択します。
+
.. ホストオペレーティングシステム（Windows または Linux など）を選択して、LUN のアライメントとブロックサイズに関する推奨デフォルト値を設定します。
.. ホストマッピンググループを選択して、どのイニシエータが LUN にアクセスできるかを制御します。


. *追加*を選択します。

