---
sidebar: sidebar 
permalink: task-dashboard-manage.html 
keywords: manage dashboard, view dashboards, edit dashboard, clone dashboard, delete dashboard, netapp console local 
summary: カスタムダッシュボードを開いたり、編集したり、複製したり、削除したりすることで、NetApp Console ローカル展開のダッシュボードを表示および管理します。 
---
= NetApp Console ローカル展開でダッシュボードを管理する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console のローカルデプロイメントでカスタムダッシュボードを管理し、ビューと運用を整合させます。チーム、フリート、優先順位の変更に応じて、ダッシュボードの編集、複製、削除を行うことができます。

このタスクは、*ストレージ* > *ダッシュボード*にあるカスタムダッシュボードにのみ適用されます。事前定義されたホームページのダッシュボードは、同じ方法では編集できません。



[[view-dashboards]]
== ダッシュボードを表示する

カスタムダッシュボードと定義済みダッシュボードを表示して、開きたい、編集したい、複製したい、または削除したいダッシュボードを見つけてください。


TIP: 定義済みのダッシュボードを複製して、編集可能なカスタムバージョンを作成できます。

.手順
. 「ストレージ」>「ダッシュボード」を選択します。
. ダッシュボードの表を確認し、開きたいダッシュボードを探してください。
. ダッシュボード名を選択して開き、その指標を確認してください。
. 必要に応じて、利用可能な操作を使用してカスタムダッシュボードを編集、複製、または削除します。




[[update-a-dashboard-as-priorities-change]]
== 優先順位が変わったらダッシュボードを更新する

業務上の優先順位が変わり、表示するカードや指標を調整する必要がある場合は、ダッシュボードを編集してください。

.手順
. 「ストレージ」>「ダッシュボード」を選択します。
. 編集したいダッシュボードを開きます。
. ダッシュボード上の既存のカードを変更するには、カードのアクションメニューから「編集」を選択します。
. *カードを追加*を選択して、ダッシュボードに新しいカードを追加します。
+
link:task-customize-dashboard-cards.html["NetApp Console ローカル展開でカードをカスタマイズする"].

. ダッシュボードを保存するには、*変更を保存*を選択してください。
+
** アクションメニューから「新しいダッシュボードとして保存」を選択することで、変更内容を新しいダッシュボードとして保存することもできます。このオプションは、他のチームやフリート向けに元のダッシュボードを維持しつつ、現在の監視ニーズに合わせて新しいバージョンを作成したい場合に便利です。
** アクションメニューから「変更を破棄」を選択することで、変更内容を破棄することもできます。このオプションは、ダッシュボードを最後に保存したバージョンに戻したい場合に便利です。






[[reuse-a-custom-dashboard-for-another-resource-or-fleet]]
== 別のリソースまたはフリートにカスタムダッシュボードを再利用する

実績のあるレイアウトを別のチーム、フリート、または監視シナリオで再利用したい場合は、ダッシュボードを複製することで、ゼロから再構築する必要がなくなります。


TIP: 定義済みのダッシュボードを複製して、編集可能なカスタムバージョンを作成できます。

.手順
. 「ストレージ」>「ダッシュボード」を選択します。
. 複製したいダッシュボードに対して、アクションメニューから*複製*を選択します。
+
コンソールのローカル展開では、元のダッシュボードのすべてのカードを含むコピーが作成されます。

. 複製したダッシュボードの名前と説明を入力してください。
. 先ほど作成した複製ダッシュボードを選択してください。新しい監視シナリオに合わせて、指標、リソース、カードの種類を変更してください。
+
link:task-customize-dashboard-cards.html["NetApp Console ローカル展開でカードをカスタマイズする"].





[[remove-dashboards-you-no-longer-use]]
== 使用しなくなったダッシュボードを削除する

現在の運用をサポートしなくなったダッシュボードを削除し、ダッシュボードリストをアクティブなユースケースに集中させておきます。

.手順
. 「ストレージ」>「ダッシュボード」を選択します。
. 削除するダッシュボードで、*削除*を選択します。
. 削除を確認します。




[[related-information]]
== 関連情報

* link:task-storage-dashboard.html["NetApp Console ローカル展開でホームページのメトリクスを表示する"]
* link:task-dashboard-get-started.html["NetApp Console ローカル展開でのダッシュボードの使用を開始する"]
* link:concept-custom-dashboards.html["NetApp Console ローカル展開におけるカスタムダッシュボードについて"]
* link:task-dashboard-create.html["カスタムダッシュボードを作成する"]
* link:task-customize-dashboard-cards.html["NetApp Console ローカル展開でダッシュボードカードをカスタマイズする"]

