---
sidebar: sidebar 
permalink: task-get-help.html 
keywords: help, ticket, open support case, support, netapp support, technical support, call support, phone number, open ticket, web ticket, open an issue 
summary: NetAppは、NetApp Console のローカル展開に対して、さまざまな方法でサポートを提供しています。ナレッジベース（KB）の記事やコミュニティフォーラムなど、充実した無料のセルフサポートオプションが24時間365日ご利用いただけます。サポート登録には、Webチケットによるリモート技術サポートが含まれています。 
---
= NetApp Consoleのローカルデプロイに関するヘルプを参照する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetAppは、NetApp Consoleのローカル展開に対するサポートをさまざまな方法で提供しています。ナレッジベース（KB）の記事やコミュニティフォーラムなど、充実した無料のセルフサポートオプションが24時間365日ご利用いただけます。NetApp Consoleのローカル展開に関連付けられたストレージリソースのシリアル番号を使用して、サポートに登録できます。登録には、Webチケットによるリモートテクニカルサポートが含まれます。



[[use-self-support-options]]
== セルフサポートオプションを利用する

これらのオプションは、24時間年中無休で無料でご利用いただけます。

* ドキュメント
+
現在ご覧になっている NetApp Console のローカルデプロイメントに関するドキュメントです。

* https://kb.netapp.com/Cloud/BlueXP["ナレッジベース"^]
+
NetApp ナレッジベースで、問題のトラブルシューティングに役立つ記事を検索してください。





[[open-a-support-case-with-netapp-console-local-deployment]]
== NetApp Consoleのローカルデプロイに関するサポートケースを開きます

NetApp Console ローカル展開環境で管理されているいずれかの NetApp ストレージシステムのシリアル番号を使用してサポートケースを開きます。

.手順
.  https://mysupport.netapp.com["NetAppサポート サイト"^]にアクセスし、NetApp Supportの資格情報でサインインします。
. 「Cases and Parts」>「Create Technical Case」を選択します。
. 問題が発生している Console ローカル展開製品に関連付けられている NetApp ストレージシステムのシリアル番号を入力してください。
. 新しいケースを作成し、NetApp Console のローカル展開に適切なカテゴリコードを選択します。




[[download-a-support-bundle]]
== サポートバンドルをダウンロード

サポートバンドルには、最新のログと構成情報が含まれています。最新のバンドルをダウンロードして、要請された場合は NetApp テクニカルサポートに送信できます。

.手順
. サポートページを表示するには、*Administration > Support* を選択してください。
. サポートカードで *作成* を選択して、ログと構成データのバンドルを作成します。
. バンドルが作成されたら、*ダウンロード*を選択してください。ZIPファイルをダウンロードするよう求められます。
+
システムは一度に1つのバンドルしか保持しません。新しいサポートバンドルを作成すると、以前のものが置き換えられます。


