---
sidebar: sidebar 
permalink: task-audit-console-activity.html 
keywords: administer, monitor, timeline, notifications, alerts, events, notification center, email, audit page, audit action 
summary: 監査ページから、ユーザーアクティビティ（UIとAPIの両方から開始されたもの）を監査できます。また、コンソールが実行している操作のステータスを監視して、対処が必要な問題がないかを確認できます。監査ページからステータスを確認したり、監査ログをお客様独自のsyslogサーバに送信するように設定したりできます。 
---
= NetApp Consoleのローカル デプロイ アクティビティの監査
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
コンプライアンスレビュー中に管理活動を文書化し、アクセス変更を確認して、NetApp Console ローカルデプロイメント全体のアクションの記録を保存します。

.必須の役割
スーパー管理者、組織管理者、フォルダおよびフリート管理者、運用サポートアナリスト、スーパービューアー、組織ビューアー、またはフォルダおよびフリートビューアー。link:reference-iam-predefined-roles.html["アクセスロールについて"]。

コンソールのローカルデプロイメントで監査アクティビティを表示し、監査ログのCSVファイルをダウンロードできます。



[[audit-user-activity-from-the-audit-page]]
== 監査ページからユーザーアクティビティを監査する

管理アクティビティを監視して、インシデントの解決時や運用上の説明責任の確認時に NetApp Console のローカル展開全体にわたる変更を追跡します。

監査ページには、組織内でユーザーが行った操作が表示されます。例えば、組織にメンバーを追加したユーザーを確認したり、ユーザーがフリートを削除したことを確認したり、組織内でユーザーが行ったその他のストレージ管理操作を表示したりできます。

監査ログには、以下のサービスのアクティビティが表示されます：

* テナント管理：ユーザーの追加、フリートの作成、リソースの関連付けなど、組織の管理に関連する操作。
* ストレージ管理：ストレージリソースの管理に関連する操作。
* フェデレーション：フェデレーションの管理に関連する操作。例えば、フェデレーションの作成、フェデレーション組織の追加または削除など。


.手順
. *「管理」>「監査」*を選択してください。
. 表の上にあるフィルターを使用して、監査アクティビティを期間、サービス、アクション、リソース、ユーザー、またはステータスで絞り込むことができます。


監査ログには、ユーザーの身元が特定できる場合に、その操作を実行したユーザーが表示されます。ユーザーの身元が特定できない場合、エントリには名前の代わりにユーザーの `auth0Id`が表示されます。

例えば、*サービス*フィルターを使用して特定のサービスに関連するアクションを表示したり、*ユーザー*フィルターを使用して特定のユーザーアカウントに関連するアクションを表示したりできます。



[[filter-audit-logs-for-identity-and-access-management-actions]]
=== IDとアクセス管理アクションの監査ログをフィルタリングする

アクセス管理の変更内容をレビューし、組織のリソースを変更した人物を確認するとともに、正確なセキュリティ調査を支援します。

.手順
. *「管理」>「監査」*を選択してください。
. フィルターを使用して結果を絞り込んでください。「サービス」を選択し、次に「テナント」を選択してください。
. 結果をさらに絞り込むには、他のフィルターを使用してください。
+
例えば、*ユーザー*フィルターを使用して、特定のユーザーアカウントによって実行されたIAMアクションを表示します。





[[download-audit-logs-from-the-audit-page]]
=== 監査ページから監査ログをダウンロードする

コンプライアンス審査や将来のインシデント調査を支援するため、組織のアクションに関する独立した記録を保存します。ダウンロードした CSV ファイルには、フィルターを適用したり表示列を変更したりした場合でも、すべての監査ログ列が含まれます。

.手順
. 「監査」ページで、表の右上隅にあるダウンロードアイコンを選択します。

