= 
:allow-uri-read: 


コンソールエージェントをインストールしてセットアップしたら、クラウド クレデンシャルを追加して、コンソールエージェントが AWS または Azure でアクションを実行するために必要な権限を持つようにします。

[role="tabbed-block"]
====
.AWS
--
.開始する前に
AWS クレデンシャルを作成したばかりの場合は、利用可能になるまで数分かかる場合があります。NetApp Console にクレデンシャルを追加する前に、数分お待ちください。

.手順
. *「管理」>「認証情報」*を選択してください。
. 「Organization credentials」を選択します。
. 「クレデンシャルの追加」を選択し、ウィザードの手順に従ってください。
+
.. *認証情報の場所*：*Amazon Web Services > Agent* を選択します。
.. *認証情報の定義*：AWSアクセスキーとシークレットキーを入力してください。
.. *マーケットプレイス サブスクリプション*：今すぐサブスクライブするか、既存のサブスクリプションを選択することで、これらのクレデンシャルにマーケットプレイス サブスクリプションを関連付けることができます。
.. *確認*：新しいクレデンシャルの詳細を確認し、*追加*を選択します。




これで https://console.netapp.com["NetApp Console"^]にアクセスして、Console エージェントの使用を開始できます。

--
.Azure
--
.開始する前に
Azure のクレデンシャルを作成したばかりの場合は、利用可能になるまで数分かかる場合があります。Console エージェントにクレデンシャルを追加する前に、数分お待ちください。

.手順
. *「管理」>「認証情報」*を選択してください。
. 「クレデンシャルの追加」を選択し、ウィザードの手順に従ってください。
+
.. *クレデンシャルの場所*：*Microsoft Azure > エージェント*を選択します。
.. *資格情報の定義*：必要なアクセス許可を付与する Microsoft Entra サービス プリンシパルに関する情報を入力します。
+
*** アプリケーション（クライアント）ID
*** ディレクトリ（テナント）ID
*** クライアントシークレット


.. *マーケットプレイス サブスクリプション*：今すぐサブスクライブするか、既存のサブスクリプションを選択することで、これらのクレデンシャルにマーケットプレイス サブスクリプションを関連付けることができます。
.. *確認*：新しいクレデンシャルの詳細を確認し、*追加*を選択します。




.結果
コンソールエージェントは、お客様に代わってAzureで操作を実行するために必要な権限を取得しました。コンソールエージェントの使用を開始するには、 https://console.netapp.com["NetApp Console"^]にアクセスしてください。

--
====