= 
:allow-uri-read: 


.開始する前に
以下のものが必要です。

* エージェントをインストールするには、root権限が必要です。
* エージェントからインターネットにアクセスするためにプロキシが必要な場合の、プロキシ サーバに関する詳細情報。
+
インストール後にプロキシ サーバを設定するオプションがありますが、そのためにはエージェントを再起動する必要があります。

* CA署名証明書（プロキシ サーバがHTTPSを使用する場合、またはプロキシが傍受プロキシである場合）。


.タスク概要
NetApp Support Siteで入手できるインストーラーは、以前のバージョンである可能性があります。インストール後、新しいバージョンが利用可能になると、エージェントは自動的にアップデートされます。

.手順
. ホストに _http_proxy_ または _https_proxy_ システム変数が設定されている場合は、削除してください：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
これらのシステム変数を削除しないと、インストールは失敗します。

. エージェントソフトウェアを https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetAppサポート サイト"^]からダウンロードし、Linuxホストにコピーします。
+
ネットワーク内またはクラウドで使用することを想定した「オンライン」エージェントインストーラーをダウンロードしてください。

. スクリプトを実行するための権限を割り当てます。
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
<version>は、ダウンロードしたエージェントのバージョンです。

. インストールスクリプトを実行します。
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxy および --cacert パラメータはオプションです。プロキシ サーバをお使いの場合は、表示されているパラメータを入力する必要があります。インストーラーはプロキシに関する情報の入力を求めません。

+
以下は、両方のオプションパラメータを使用したコマンドの例です。

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy は、エージェントが以下のいずれかの形式を使用して HTTP または HTTPS プロキシ サーバを使用するように設定します：

+
** \http://address:port
** http://user-name:password@address:port
** \http://domain-name%92user-name:password@address:port
** \https://address:port
** \https://user-name:password@address:port
** \https://domain-name%92user-name:password@address:port
+
次の点に注意してください。

+
*** ユーザーはローカルユーザーまたはドメインユーザーのいずれかです。
*** ドメインユーザーの場合は、上記のようにバックスラッシュ（\）のASCIIコードを使用する必要があります。
*** エージェントは、@文字を含むユーザー名またはパスワードをサポートしていません。
*** パスワードに次の特殊文字が含まれている場合は、その特殊文字の前にバックスラッシュを付けてエスケープする必要があります：& または !
+
次に例を示します。

+
\http://bxpproxyuser:netapp1\!@address:3128





+
--cacert は、エージェントとプロキシ サーバ間の HTTPS アクセスに使用する CA 署名証明書を指定します。このパラメータは、HTTPS プロキシ サーバを指定する場合、またはプロキシが傍受プロキシである場合にのみ必要です。

. Podmanを使用している場合は、aardvark-dnsのポートを調整する必要があります。
+
.. エージェント仮想マシンにSSH接続します。
.. podman _/usr/share/containers/containers.conf_ ファイルを開き、Aardvark DNSサービス用に選択したポートを変更します。たとえば、54 に変更します。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. エージェント仮想マシンを再起動してください。




. インストールが完了するまでお待ちください。
+
インストールの終了時に、プロキシ サーバを指定した場合、エージェント サービス （occm） が 2 回再起動します。

. エージェント仮想マシンに接続されているホストからWebブラウザを開き、次のURLを入力してください：
+
https://_ipaddress_[]

. ログイン後、エージェントを設定します。
+
.. エージェントに関連付けるコンソール組織を指定します。
.. システムの名前を入力してください。
.. 「セキュリティで保護された環境で実行していますか？」の下の制限モードは無効のままにしてください。
+
これらの手順では標準モードでのコンソールの使用方法を説明しているため、制限モードは無効にしておく必要があります。安全な環境が整っていて、このアカウントをコンソールのバックエンドサービスから切断したい場合にのみ、制限モードを有効にしてください。もしそうなら、link:task-quick-start-restricted-mode.html["制限モードで NetApp Console を使い始めるには、以下の手順に従ってください"]。

.. 「Let's start」を選択してください。



